name        = "rusty sword"
description = "Just a simple rusty sword, pock-marked but tried and true."
target_name = ["rusty sword", "sword", "simple sword"]
type        = "weapon"
power       = 2
durability  = 10
value       = 2

[hooks]
    [hooks.onHit]
        code = """
        var chance = random(1, 100)
        
        if chance < target.get_vitality() then 
            send(target, \"Ouch, that hurt! Better go get checked for tetanus!\")
            send(attacker, \"You gave your enemy a bit of extra sting with that one!\")
            target.apply_effect("poison", 10, 2)
        endif
               """

